name: preview
on: 
    pull_request:
        branches:
            - main
            - build-apk
            - eas-build
            - M*
    push:
        branches:
            - main
            - build-apk
            - eas-build
            - M*
            - operator-login

jobs:
  update:
    name: EAS Update
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: write
    steps:
      - name: Check for EXPO_TOKEN
        run: |
          if [ -z "${{ secrets.EXPO_TOKEN }}" ]; then
            echo "You must provide an EXPO_TOKEN secret linked to this project's Expo account in this repo's secrets. Learn more: https://docs.expo.dev/eas-update/github-actions"
            exit 1
          fi

      - name: Create Google Services JSON File
        env:
            GOOGLE_SERVICES_JSON: ${{ secrets.GOOGLE_SERVICES }}
        run: echo $GOOGLE_SERVICES_JSON | base64 -di > ./google-services.json

      - name: Create eas.json File
        env:
            EAS_JSON: ${{ secrets.EAS }}
        run: echo $EAS_JSON | base64 -di > ./eas.json

      - name: Create app.json File
        env:
            APP_JSON: ${{ secrets.APP_JSON }}
        run: echo $APP_JSON | base64 -di > ./app.json

      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: npm

      - name: Setup EAS
        uses: expo/expo-github-action@v8
        with:
          eas-version: latest
          token: ${{ secrets.EXPO_TOKEN }}

      - name: Install dependencies
        run: npm install

      - name: Create preview
        uses: expo/expo-github-action/preview@v8
        with:
          command: eas update --auto